version: "3"

services:
  db:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=qa
    ports:
      - "5444:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - "8000"
    links:
      - db:db
    # volumes:
    #   - ./:/app
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db-data:
