version: "3"

services:
  postgres:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=qa
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - ./:/app
    env_file:
      - .env
    command: python /app/manage.py runserver --host 0.0.0.0 --port 5432 --threaded

volumes:
  db-data:
